import { PORT_LABELS, LIMITS } from '../../shared/constants.js';

export { PORT_LABELS, LIMITS };

export const WINDOW_DURATIONS_MS = {
  '1m': 60_000,
  '5m': 300_000,
  '15m': 900_000,
  '1h': 3_600_000,
};

export const SUBNET_PARENT_MAP = {
  '/24': '/16',
  '/16': '/8',
};

export const VALIDATION_RULES = {
  EPS_MIN: LIMITS.EPS_MIN,
  EPS_MAX: LIMITS.EPS_MAX,
  PORT_MIN: 1,
  PORT_MAX: 65535,
  VALID_PROTOCOLS: ['TCP', 'UDP', 'ICMP'],
};

export const AGGREGATOR_DEFAULTS = {
  TOP_SUBNETS_COUNT: 5,
  MAX_SUBNETS_IN_SNAPSHOT: 30,
  SNAPSHOT_INTERVAL_MS: 1000,
  TOP_IPS_COUNT: 10,
  TOP_PORTS_COUNT: 5,
};

export const REMOTE_DEFAULTS = {
  POLLING_INTERVAL_MS: 2000,
  POLLING_TIMEOUT_MS: 5000,
  MAX_EVENTS_PER_POLL: 10_000,
  MAX_AGENTS: 20,
};

export const AGENT_DEFAULTS = {
  BUFFER_CAPACITY: 100_000,
  DEFAULT_EVENT_LIMIT: 10_000,
  MAX_EVENT_LIMIT: 50_000,
};
